### ISSUE TITLE
Create competitive load tests

### ISSUE THREAD

**Issue by dmitry-erokhin** [Dmitry-Erokhin/zq#22]
**As** a developer
**I want to** create a competitive performance test suite
**So that** I will be able to assess library performance (against pgq initially) under same load patterns

## Tasks
- [ ] Create a performance test cases scenarios
- [ ] Choose a library (with nice reporting)
- [ ] Design abstraction layer 
- [ ] Create zq implementation for abstraction
- [ ] Create pgq implementation for the abstraction
- [ ] Implement test suite using given library
- [ ] Create gradle runner for this test suite
